latent_dim = 2
n_epochs = 5000
lr = 1e-4
add_noise_scale = 0.15

# DAA loss weights
at_loss_factor = 10.0  # 80.0
class_loss_factor = 1.0  # 80.0
recon_loss_factor = 1.0  # 1.0
kl_loss_factor = 1.0  # 40.0

network = "INN"  # TODO
interpolation = "slerp"
weight_norm_exp = 1.0
weight_norm_constraint = 1.0

add_image_noise = 0.15

ncl = 10
img_width = 32
conditional = true
