model_type = "INN"

dataset = "EMNIST"

n_epochs = 1500

n_channels = 1
img_width = 32
n_classes = 10

lr = 1e-4
beta1 = 0.9
beta2 = 0.999
weight_decay = 1e-5
lr_step = 0.1
add_image_noise = 0.3

coupling_type = "GLOW"
clamping = 1.5
latent_dist = "normal"
use_min_likelihood = false
lambda_mll = 1.0

latent_dim = 9
use_proto_z = false
interpolation = "linear"
load_inn = false
weight_norm_exp = 1.0
weight_norm_constraint = 1.0
fix_inn = false
fix_z_arch = true
lambda_at = 10.0
lambda_recon = 1.0
lambda_class = 1.0
lambda_proto = 100.0
