model_type = "INN"

dataset = "EMNIST"

n_epochs = 1500

n_channels = 1
img_width = 32
n_classes = 10

lr = 1e-4
beta1 = 0.9
beta2 = 0.999
weight_decay = 1e-5
lr_step = 0.1
add_image_noise = 0.15

coupling_type = "GLOW"
conditional = true
internal_width1 = 16
internal_width2 = 32
clamping = 1.5
latent_dist = "normal"
use_min_likelihood = false
lambda_mll = 1.0
n_conv_high_res = 4
n_conv_low_res = 4
n_fc = 2

latent_dim = 2
use_proto_z = false
z_from_similar = false
z_per_class = false
interpolation = "linear"
load_inn = ''
weight_norm_exp = 1.0
weight_norm_constraint = 1.0
fix_inn = false
fix_z_arch = true
lambda_nll = 0.1
lambda_at = 10.0
lambda_recon = 80.0
lambda_class = 1.0
lambda_proto = 100.0
lambda_jac = 0
aa_weights_max = 1.0
aa_weights_min = 0.0
aa_allow_negative = false
aa_weights_noise = 0.0
load_ib_inn = ''
nullspace_split = false
aa_bias = true
soft_constraint = false
lambda_constraint = 1.0
